### ISSUE TITLE
Failed to start jupyterlab notebooks

### ISSUE THREAD

**Issue by karbyshevds** [odahu/odahu-flow-jupyterlab-plugin#41]
```
 Error: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for dmitriy_karbyshev@epam.com may contain details.) 
```
jupyterhub logs:
```
[D 2020-09-25 16:20:59.057 JupyterHub spawner:1850] .. overriding KubeSpawner value image=gcr.io/or2-msq-epmd-legn-t1iylu/odahu/datascience-notebook:1.3.0-rc1
[D 2020-09-25 16:20:59.057 JupyterHub base:613] Initiating spawn for dmitriy_karbyshev@epam.com
[D 2020-09-25 16:20:59.058 JupyterHub base:619] 0/64 concurrent spawns
[D 2020-09-25 16:20:59.058 JupyterHub base:622] 0 active servers
[E 2020-09-25 16:20:59.088 JupyterHub user:477] Unhandled error starting dmitriy_karbyshev@epam.com's server: '<' not supported between instances of 'NoneType' and 'NoneType'
[D 2020-09-25 16:20:59.094 JupyterHub user:578] Deleting oauth client jupyterhub-user-dmitriy_karbyshev%40epam.com
[E 2020-09-25 16:20:59.103 JupyterHub gen:593] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py:629> exception=TypeError("'<' not supported between instances of 'NoneType' and 'NoneType'",)> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 589, in error_callback
        future.result()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 636, in finish_user_spawn
        await spawn_future
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 489, in spawn
        raise e
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/user.py", line 409, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1636, in _start
        events = self.events
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 1491, in events
        for event in self.event_reflector.events:
      File "/usr/local/lib/python3.6/dist-packages/kubespawner/spawner.py", line 72, in events
        key=lambda x: x.last_timestamp,
    TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
 [W 2020-09-25 16:20:59.104 JupyterHub base:699] 4 consecutive spawns failed.  Hub will exit if failure count reaches 5 before succeeding
[E 2020-09-25 16:20:59.104 JupyterHub pages:148] Failed to spawn single-user server with form
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/pages.py", line 146, in post
        await self.spawn_single_user(user, options=options)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 737, in spawn_single_user
        status, spawner._log_name))
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for dmitriy_karbyshev@epam.com may contain details.)
```

**Comment by vlad-tokarev** [comment]
Can't reproduce
